import Head from 'next/head'
import React, { Fragment } from 'react'
import Footer from './Footer'
import Header from './Header'

interface Props {
  children: React.ReactNode
}
const Layout: React.FC<Props> = ({ children }) => {
  return (
    <Fragment>
      <Head>
        <title>Create T3 Note App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-screen">
        <Header />
        <main className=" mx-auto pb-64 sm:max-w-7xl">{children}</main>
        <Footer />
      </div>
    </Fragment>
  )
}

export default Layout
